GET http://localhost:8000/api/facts/Billionaire%20Charles%20Koch-Backed%20Group%20Will%20Push%20GOP%20to%20Move%20Past%20Donald%20Trump

###

PUT http://localhost:8000/api/facts/fact1/upvote

###

POST http://localhost:8000/api/facts/fact1/comments
content-type: application/json

{
    "postedBy": "emma",
    "text": "Hmm.. I have a different standpoint"
}