GET http://localhost:8000/api/facts/fact1

###

PUT http://localhost:8000/api/facts/fact1/upvote

###

POST http://localhost:8000/api/facts/fact1/comments
content-type: application/json

{
    "postedBy": "emma",
    "text": "Hmm.. I have a different standpoint"
}