GET http://localhost:8000/api/facts/fact2

###

PUT http://localhost:8000/api/facts/fact1/upvote

###

POST http://localhost:8000/api/facts/user1&2/comments
content-type: application/json

{
    "postedBy": "james",
    "text": "this is biased.."
}